[package]
name = "my-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
mini-redis = "0.4"
bytes = "1.10.1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
serde_json = "1.0"
