name: Check for conventional commit

on:
  pull_request:
    types: [opened, ready_for_review, edited, reopened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-cc:
    name: Check for conventional commit
    runs-on: ubuntu-latest
    steps:
      - uses: agenthunt/conventional-commit-checker-action@v2.0.0
        with:
          pr-title-regex: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\((\w|-)+\))?(!)?: (.+)$'
